services:

  app:
    container_name: app
    build: .
    restart: always
    ports:
      - "8000:8000"
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env    
    networks:
      - docker_network

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./core/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./core/nginx/conf.d:/etc/nginx/conf.d
      - ./core/static:/usr/share/nginx/html/static
    depends_on:
      - app      
    command: nginx -g "daemon off;"
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge
